name: Code QA Roo Cline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches: [main]

jobs:
  code-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cached install
        uses: RooVetGit/Roo-GHA/.github/actions/setup-node-cache-and-install@main
        with:
          node-version: "18"
          clean-install: false

      - name: Install dependencies
        run: npm run install:all

      - name: Compile TypeScript
        run: npm run compile
